### PR TITLE
Close tab notification opera

### LINKED ISSUE #241: Closing tab notification doesn't reactivate opener tab in Opera
When the tab notification is opened in Opera and user clicks on the action button (focus, short break, long break) the tab is closed and previous tab is not reactivated as it was intended and actually happens in chrome. The last tab to the right in current window is the one that is activated instead.

### PR DESCRIPTION
**Pull request by dbautistav**
Fixes #241 - Issue seen in Opera, change effects all browsers.

### CODE REVIEW

**Comment by schmich** [comment]
Thanks for the contribution!

I'm doing a pretty significant refactoring in another branch to help manage the complexity of this extension going forward, but I don't think it interferes with this change at all. I need to do a bit of cleanup, but I should be able to merge this soon.

**Comment by dbautistav** [comment]
Please let me know if you need help integrating this changes or with the ongoing refactoring/cleanup.

**Comment by schmich** [comment]
This change looks good. Thanks for the contribution! I will release a new version soon.

Side note/rant: It's a bit of a bummer that these browsers have adopted Chrome's extension API, but interpret it so differently. I foresee a bunch of corner cases and browser-specific quirks despite them sharing the "standard". It's like HTML/CSS all over again, but I suppose the fact that it works at all across different browsers is better than nothing!

**Comment by dbautistav** [comment]
> _"It's a bit of a bummer that these browsers have adopted Chrome's extension API, but interpret it so differently."_
It is, indeed.

> _"I foresee a bunch of corner cases and browser-specific quirks despite them sharing the "standard"."_
In this regards, have you decided if it is there going to be one marinara version per browser or is it going to be the same version but trying to handle each case specifically?

> _"... but I suppose the fact that it works at all across different browsers is better than nothing!"_
Definitively.

Finally @schmich, thank you for integrating my proposed changes!    :D

**Comment by schmich** [comment]
> have you decided if it is there going to be one marinara version per browser or is it going to be the same version but trying to handle each case specifically?

I'd like to keep it simple by publishing the same version/package from the same code base across all browsers and environments.

I definitely don't have the time right now to maintain versions that target other native browser APIs (e.g. targetting Opera's extension API in Opera instead of relying on Opera's Chrome extension API compatibility). That might happen eventually, but it's just too much at the moment.

I haven't really used the extension much outside of Chrome besides verifying bugs. Just so I fully understand, how did you install Marinara in Opera? Did you install Opera's ["Install Chrome Extensions" extension](https://addons.opera.com/en/extensions/details/install-chrome-extensions/) and _then_ install Marinara from the Chrome Web Store?

**Pull request merged**
