### PR TITLE
Added Norwegian translation with the no tag

### PR DESCRIPTION
**Pull request by wkillerud**
The request for translation requested Norwegian with the "no" tag. 

For future reference, Norway has two written languages - Norwegian Bokmål (nb-NO) and Norwegian Nynorsk (nn-NO). This translation is for Norwegian Bokmål (nb-NO), which is the more used of the two. While different, readers of one language can understand the other just fine (at least native speakers). Being proficient in writing both is another matter, so I won't do nn-NO readers the disservice of trying to translate :P

### CODE REVIEW

**Comment by schmich** [comment]
Mange takk! That difference is fascinating. It's impressive how complex language and communication can be.

The `no` locale ID is from Chrome's own [supported locale table](https://developer.chrome.com/webstore/i18n#localeTable). I'm surprised they don't break it into sublocales like you mention. Even Google Translate refers to the language as just "Norwegian" without being more specific. It looks like Bokmål has majority mindshare, so perhaps Google settled on that as de facto written Norwegian.

Thanks again for your contribution!

**Comment by wkillerud** [comment]
I figured it could be a limitation from Chrome, but it surprises me they have just the one. Firefox supports both locales. The power of open source I guess ;) Thanks for merging!

**Comment by schmich** [comment]
I'm going to rename the `no` folder to `nb`. Right now, with `no`, Chrome does not load the translations. As it turns out, there's a [Chrome doc bug](https://bugs.chromium.org/p/chromium/issues/detail?id=85075) that they haven't fixed...in 6 years.

The locale table is supposed to have `nb` for Norwegian (which matches your `nb-NO`/`nn-NO` descriptions), but I guess someone was confused and wrote `no`.

Thanks for the heads-up, it would've taken me a while longer to track this bug down without your explanation.

**Comment by wkillerud** [comment]
> There's a Chrome doc bug that they haven't fixed...in 6 years.

Yikes! I know we're a (globally speaking) small user group in Norway, but wow! Glad my explanation helped you track down the issue 😄

**Pull request merged**
