### PR TITLE
Update translation for es locale

### PR DESCRIPTION
**Pull request by mcmtradu**

### CODE REVIEW

**Comment by schmich** [comment]
Awesome! I'm going through this now.

Quick question: I noticed the menu entries are now sentence cased (e.g. `start_pomodoro_cycle`). They were originally capitalized to match the Chrome menu styles on Mac (notice they're all Title Cased below). Unfortunately, it looks like Chrome uses "Casing like this" on Windows, so it's inconsistent between platforms. Given that the platforms use different casing, would you recommend sentence case or Title Case?

screen shot 2018-02-23 at 10 58 31 am

The rest looks great. Thanks for updating and filling in the gaps. I didn't even notice the "Aviso Legal" placeholder before...oops.

**Comment by mcmtradu** [comment]
Hi,

I have put all the entries in lower case so that they follow the Spanish grammar rules. Moreover, Chrome menu styles are sentence cased for Spanish in both Mac and Windows. That's why I'd recommend keeping them sentence cased. You can see the Mac version below:
captura de pantalla 2018-02-23 a la s 19 24 03

However, if you prefer that they are capitalized to keep the consistency with the English version, I'll be happy to make the changes. :smiley:

**Comment by schmich** [comment]
Perfect. Even better that it's consistent across platforms for Spanish. Thanks again for the contribution. I encourage you to add yourself to the [contributors list](https://github.com/schmich/marinara/blob/master/CONTRIBUTORS.md).

I am going to publish this to the Chrome Web Store soon, but I will hold off if you still intend to add Catalan translations (no pressure, and no problem if not).

**Comment by mcmtradu** [comment]
Great! Thank you for the app! It's really helping me boost my productivity, and what a better way to show my appreciation that helping with the translation.

I plan to finish the Catalan translation over the weekend. I will add myself to the contributors list when doing the pull request.

**Pull request merged**
